#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_ARITHMETIC_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_ARITHMETIC_H

#include "add.h"
#include "cmp.h"
#include "dec.h"
#include "inc.h"
#include "sub.h"

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_ARITHMETIC_H
