#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_ARITHMETIC_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_ARITHMETIC_H

#include "add.h"
#include "cmp.h"

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_ARITHMETIC_H
