#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_CONTROL_TRANFER_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_CONTROL_TRANFER_H

#include "call.h"
#include "interrupts.h"
#include "jump.h"

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_CONTROL_TRANFER_H
