#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_DATA_TRANSFER_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_DATA_TRANSFER_H

#include "lea.h"
#include "mov.h"
#include "pop.h"
#include "push.h"
#include "xchg.h"

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_DATA_TRANSFER_H
