#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_LOGIC_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_LOGIC_H

#include "or.h"
#include "shift.h"
#include "test.h"
#include "xor.h"

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_LOGIC_H
