#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_PROCESSOR_CONTROL_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_PROCESSOR_CONTROL_H

#include "../../models/emulator.h"

void hlt_exec(emulator_t *emulator, params_t params);

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_PROCESSOR_CONTROL_H
