#ifndef EMULATOR_INSTRUCTIONS_IMPLEMENTATION_UTILS_H
#define EMULATOR_INSTRUCTIONS_IMPLEMENTATION_UTILS_H

unsigned char get_parity(unsigned short value);

#endif // !EMULATOR_INSTRUCTIONS_IMPLEMENTATION_UTILS_H
