#ifndef EMULATOR_MINIX_ENV_H
#define EMULATOR_MINIX_ENV_H

#define SYSCALL_NOT_FOUND 0
#define SYSCALL_EXIT 1
#define SYSCALL_FORK 2
#define SYSCALL_READ 3
#define SYSCALL_WRITE 4
#define SYSCALL_OPEN 5
#define SYSCALL_CLOSE 6
#define SYSCALL_WAIT 7
#define SYSCALL_CREATE 8

#endif // !EMULATOR_MINIX_ENV_H
